### ISSUE TITLE
No AppsToKnow icon

### ISSUE THREAD

**Issue by wertyui6795** [AppsToKnow/yRecycle#2]
please add the ATK icon. i need it for further dev in the SDK.

**Comment by AppsToKnow** [comment]
Hope you had a good Christmas and New year.

I do not have a logo for ATK, so I have attached  the image I am using for the App Icon in case that is what you need.

Note that I have been modifying the student write-ups as I have been inserting them into the App. I am not done yet, so hold off with putting them into your app until early next week.

Michael.

**Comment by wertyui6795** [comment]
i will hold off, i need more time. ms. fandrey is rushing me. if she rushes me, i will have loops and stuff. i need time.

**Comment by wertyui6795** [comment]
Hello, should i still continue to develop the app?

**Comment by AppsToKnow** [comment]
I think it would be great if you did, it would make the app available to a lot more people. 

I will help as much as I can, but I have no experience with android.

Thanks for your continued interest. 

Michael Stephenson, AIA

**Comment by wertyui6795** [comment]
hello mr. stephenson, should we update this and push it to apple? if you want me to add/improve the app and it's contents? if we could get together and work on getting this to android or whatever, I am now more capable than I was in 8th grade.
- Ethan Payne -

**Comment by AppsToKnow** [comment]
Thanks for the interest.

I have pretty much stopped developing software, but I still have my Apple Developer license. It takes a lot of time and I have not made enough off the apps to cover the costs.

If you want I can give you a copy of the yRecycle code so that you can do some updates. Note that the software will only run on an Apple computer that has Xcode installed. Since the App is through my account, I am the only one that can upload any updated to the App Store.

Be forewarned that I had some trouble running the code on another computer. I will try to get that sorted out before I send the code, but that may take me a few days.

Michael
